// <auto-generated />
using System;
using ArticleDatabaseConnector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArticleDatabaseConnector.Migrations
{
    [DbContext(typeof(ArticleContext))]
    [Migration("20210829145913_Data-Seed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArticleDatabaseConnector.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d0bd269-da9b-4343-9d4e-da9b67f2fdb0"),
                            AuthorId = 9,
                            Category = "Religion",
                            DatePublished = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 43,
                            Title = "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."
                        },
                        new
                        {
                            Id = new Guid("9b68e86c-a0ef-4060-b0e3-4d23fe5e6df7"),
                            AuthorId = 5,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 2,
                            Title = "Morbi a ipsum."
                        },
                        new
                        {
                            Id = new Guid("83b2f6c5-4240-46cd-b3c9-80a48a964059"),
                            AuthorId = 5,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 4,
                            Title = "Praesent blandit lacinia erat."
                        },
                        new
                        {
                            Id = new Guid("1cb17245-c17a-4f0c-b655-fde3cd83584d"),
                            AuthorId = 8,
                            Category = "News",
                            DatePublished = new DateTime(2021, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 57,
                            Title = "Quisque id justo sit amet sapien dignissim vestibulum."
                        },
                        new
                        {
                            Id = new Guid("e257513f-7336-4a7e-962d-692f2de2c29f"),
                            AuthorId = 1,
                            Category = "News",
                            DatePublished = new DateTime(2020, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 21,
                            Title = "Proin interdum mauris non ligula pellentesque ultrices."
                        },
                        new
                        {
                            Id = new Guid("47c7adb1-1272-4c14-9dd7-cf0024908b06"),
                            AuthorId = 6,
                            Category = "Religion",
                            DatePublished = new DateTime(2020, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 21,
                            Title = "Aliquam erat volutpat."
                        },
                        new
                        {
                            Id = new Guid("3a44435b-caad-405a-a89d-9983822c88b3"),
                            AuthorId = 4,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 18,
                            Title = "Praesent lectus."
                        },
                        new
                        {
                            Id = new Guid("eb8d6755-c5df-4c2e-a0d6-3cf040a0049e"),
                            AuthorId = 5,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 74,
                            Title = "Curabitur gravida nisi at nibh."
                        },
                        new
                        {
                            Id = new Guid("a375a55c-142e-4c09-9c39-15961c8684b7"),
                            AuthorId = 9,
                            Category = "News",
                            DatePublished = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 83,
                            Title = "Vivamus vestibulum sagittis sapien."
                        },
                        new
                        {
                            Id = new Guid("340e462c-db42-427c-b78d-76bf0c687440"),
                            AuthorId = 9,
                            Category = "Religion",
                            DatePublished = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 99,
                            Title = "Praesent blandit lacinia erat."
                        },
                        new
                        {
                            Id = new Guid("29635df6-a1bc-48f7-a40e-a20d025d2be9"),
                            AuthorId = 7,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 34,
                            Title = "Donec ut dolor."
                        },
                        new
                        {
                            Id = new Guid("1d477e94-e22b-4967-95c6-e94d61618b02"),
                            AuthorId = 1,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 22,
                            Title = "Maecenas tincidunt lacus at velit."
                        },
                        new
                        {
                            Id = new Guid("b0346fc4-4215-4461-883a-1c9812177b5e"),
                            AuthorId = 9,
                            Category = "Sports",
                            DatePublished = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 23,
                            Title = "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem."
                        },
                        new
                        {
                            Id = new Guid("b22d2d99-3983-4833-a6ec-4e4399ae020b"),
                            AuthorId = 9,
                            Category = "Style",
                            DatePublished = new DateTime(2021, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 68,
                            Title = "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo."
                        },
                        new
                        {
                            Id = new Guid("5ea93e35-3fa0-4418-b22b-d53442bab6b5"),
                            AuthorId = 5,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 79,
                            Title = "Suspendisse potenti."
                        },
                        new
                        {
                            Id = new Guid("651ef77c-9381-4d91-9b99-3a24c67949f2"),
                            AuthorId = 9,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 36,
                            Title = "In quis justo."
                        },
                        new
                        {
                            Id = new Guid("50d8d1d7-65f3-4d65-9f36-d16dde6ee110"),
                            AuthorId = 9,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 65,
                            Title = "Pellentesque eget nunc."
                        },
                        new
                        {
                            Id = new Guid("ec964392-e77c-4656-ab58-ce93624978e7"),
                            AuthorId = 9,
                            Category = "Religion",
                            DatePublished = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 34,
                            Title = "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla."
                        },
                        new
                        {
                            Id = new Guid("f46f2691-ce98-4e6b-986f-5076e7369c7c"),
                            AuthorId = 3,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 48,
                            Title = "Morbi non lectus."
                        },
                        new
                        {
                            Id = new Guid("c183d7e1-afd2-4ca9-be2d-2de2f633e47f"),
                            AuthorId = 7,
                            Category = "Religion",
                            DatePublished = new DateTime(2020, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 21,
                            Title = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
                        },
                        new
                        {
                            Id = new Guid("5a0b087b-4b17-449a-b15c-9820329c2dda"),
                            AuthorId = 7,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 45,
                            Title = "Curabitur gravida nisi at nibh."
                        },
                        new
                        {
                            Id = new Guid("9eb1fdba-fd56-4b07-892a-3281bf830e2f"),
                            AuthorId = 1,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2020, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 33,
                            Title = "Nulla tempus."
                        },
                        new
                        {
                            Id = new Guid("8f8c649b-201e-4715-bf71-f0a44450290b"),
                            AuthorId = 3,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 68,
                            Title = "Morbi ut odio."
                        },
                        new
                        {
                            Id = new Guid("5d052b97-53d2-43f3-8bbf-3d64aaaab5c9"),
                            AuthorId = 2,
                            Category = "Religion",
                            DatePublished = new DateTime(2021, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 88,
                            Title = "Mauris sit amet eros."
                        },
                        new
                        {
                            Id = new Guid("7be5d7f6-63ec-4b21-a78c-7eb6d75833c9"),
                            AuthorId = 10,
                            Category = "Sports",
                            DatePublished = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 27,
                            Title = "Sed sagittis."
                        },
                        new
                        {
                            Id = new Guid("773d30d3-be84-4d88-bcc1-1fc7e2563e8c"),
                            AuthorId = 6,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 15,
                            Title = "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo."
                        },
                        new
                        {
                            Id = new Guid("994ebaf2-3c1a-46a9-815a-a2a4f7d08e3d"),
                            AuthorId = 5,
                            Category = "Religion",
                            DatePublished = new DateTime(2021, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 15,
                            Title = "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla."
                        },
                        new
                        {
                            Id = new Guid("5a613a14-8989-403d-b87c-4c1d39172712"),
                            AuthorId = 7,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 57,
                            Title = "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."
                        },
                        new
                        {
                            Id = new Guid("2a803f30-4635-40c9-a463-dbc09500bbe1"),
                            AuthorId = 6,
                            Category = "Style",
                            DatePublished = new DateTime(2021, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 79,
                            Title = "Duis mattis egestas metus."
                        },
                        new
                        {
                            Id = new Guid("602bacae-6323-4d51-95ed-02ebdf574ad0"),
                            AuthorId = 4,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 2,
                            Title = "Sed sagittis."
                        },
                        new
                        {
                            Id = new Guid("334ea2ac-e701-43c5-9d68-b957f9538545"),
                            AuthorId = 7,
                            Category = "Sports",
                            DatePublished = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 95,
                            Title = "Nulla suscipit ligula in lacus."
                        },
                        new
                        {
                            Id = new Guid("aa798188-b1c3-4300-974b-7fe9c3584988"),
                            AuthorId = 4,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 82,
                            Title = "Duis at velit eu est congue elementum."
                        },
                        new
                        {
                            Id = new Guid("d7790170-d5fa-4ac6-acba-670f9b157d7f"),
                            AuthorId = 4,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 26,
                            Title = "Integer tincidunt ante vel ipsum."
                        },
                        new
                        {
                            Id = new Guid("656b25a3-16db-42cc-a682-3110997c2ca5"),
                            AuthorId = 9,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 63,
                            Title = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
                        },
                        new
                        {
                            Id = new Guid("7f0c6203-8727-4a0a-9419-b05dec681a19"),
                            AuthorId = 4,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 83,
                            Title = "Suspendisse potenti."
                        },
                        new
                        {
                            Id = new Guid("961c5eea-6e93-455e-9faa-57872b0b45c8"),
                            AuthorId = 8,
                            Category = "News",
                            DatePublished = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 8,
                            Title = "Nulla ut erat id mauris vulputate elementum."
                        },
                        new
                        {
                            Id = new Guid("7423f6db-c807-4bc7-ad47-633f47e32f8a"),
                            AuthorId = 4,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 90,
                            Title = "Morbi porttitor lorem id ligula."
                        },
                        new
                        {
                            Id = new Guid("a1101e28-0163-4fc6-ad18-2c797d94e792"),
                            AuthorId = 10,
                            Category = "Sports",
                            DatePublished = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 96,
                            Title = "Vivamus tortor."
                        },
                        new
                        {
                            Id = new Guid("8a69d105-c700-44bb-b893-3aeef5dd428c"),
                            AuthorId = 4,
                            Category = "News",
                            DatePublished = new DateTime(2020, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 41,
                            Title = "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."
                        },
                        new
                        {
                            Id = new Guid("e5d93925-60b4-476a-8414-908b2a6320d6"),
                            AuthorId = 7,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 99,
                            Title = "Proin eu mi."
                        },
                        new
                        {
                            Id = new Guid("fbcd0e8f-c072-4c3d-88ac-9f33317bd7c2"),
                            AuthorId = 5,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2020, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 37,
                            Title = "Ut tellus."
                        },
                        new
                        {
                            Id = new Guid("4781fbfa-f120-4c9f-a40f-03767e64500f"),
                            AuthorId = 2,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 37,
                            Title = "Maecenas pulvinar lobortis est."
                        },
                        new
                        {
                            Id = new Guid("8e86339e-c0ea-48c2-a8e3-4322db832482"),
                            AuthorId = 9,
                            Category = "Religion",
                            DatePublished = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 53,
                            Title = "Morbi vel lectus in quam fringilla rhoncus."
                        },
                        new
                        {
                            Id = new Guid("973ba922-bd22-4d48-a8d2-fcf572ed3b4b"),
                            AuthorId = 4,
                            Category = "Religion",
                            DatePublished = new DateTime(2020, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 60,
                            Title = "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl."
                        },
                        new
                        {
                            Id = new Guid("5cc04767-6613-45b5-8194-16be334a5fee"),
                            AuthorId = 9,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 77,
                            Title = "Quisque id justo sit amet sapien dignissim vestibulum."
                        },
                        new
                        {
                            Id = new Guid("6ae75438-4b1d-4989-9ef6-a827baac4930"),
                            AuthorId = 8,
                            Category = "Sports",
                            DatePublished = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 14,
                            Title = "In sagittis dui vel nisl."
                        },
                        new
                        {
                            Id = new Guid("f855209b-2268-4984-8a40-f90bf5db9e06"),
                            AuthorId = 6,
                            Category = "Style",
                            DatePublished = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 44,
                            Title = "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue."
                        },
                        new
                        {
                            Id = new Guid("c0627ec7-b75e-4990-aa18-43646f97c2ea"),
                            AuthorId = 4,
                            Category = "News",
                            DatePublished = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 72,
                            Title = "Praesent blandit."
                        },
                        new
                        {
                            Id = new Guid("49d471c2-85ad-4b5b-90b1-156c5d6811e9"),
                            AuthorId = 3,
                            Category = "News",
                            DatePublished = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 88,
                            Title = "Duis consequat dui nec nisi volutpat eleifend."
                        },
                        new
                        {
                            Id = new Guid("9536bf6f-2043-4adf-934c-a548f3956feb"),
                            AuthorId = 8,
                            Category = "News",
                            DatePublished = new DateTime(2021, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 83,
                            Title = "In est risus, auctor sed, tristique in, tempus sit amet, sem."
                        },
                        new
                        {
                            Id = new Guid("754165ca-fc19-412d-8fc4-8499e773fc29"),
                            AuthorId = 2,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 96,
                            Title = "Vivamus tortor."
                        },
                        new
                        {
                            Id = new Guid("140eb5b5-2791-4916-a96f-282cffaeb99d"),
                            AuthorId = 4,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 23,
                            Title = "Phasellus id sapien in sapien iaculis congue."
                        },
                        new
                        {
                            Id = new Guid("efc825df-d8ec-4ec3-b540-05e973277df2"),
                            AuthorId = 8,
                            Category = "Sex",
                            DatePublished = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 61,
                            Title = "Proin eu mi."
                        },
                        new
                        {
                            Id = new Guid("13eecd61-11f2-4586-8d99-5d55ae1f64da"),
                            AuthorId = 10,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 23,
                            Title = "In hac habitasse platea dictumst."
                        },
                        new
                        {
                            Id = new Guid("f891e64d-32b6-44ce-a75f-19594af461cb"),
                            AuthorId = 8,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 80,
                            Title = "Praesent lectus."
                        },
                        new
                        {
                            Id = new Guid("5a1a6e4c-2acd-4d1b-a19e-65f8dbc8a219"),
                            AuthorId = 7,
                            Category = "Style",
                            DatePublished = new DateTime(2020, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 29,
                            Title = "Proin at turpis a pede posuere nonummy."
                        },
                        new
                        {
                            Id = new Guid("bd39f1a9-ef56-484c-8443-3f3ba3087ff4"),
                            AuthorId = 1,
                            Category = "News",
                            DatePublished = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 47,
                            Title = "Duis aliquam convallis nunc."
                        },
                        new
                        {
                            Id = new Guid("d73cfb87-b28c-4888-9a44-35a27758fc4a"),
                            AuthorId = 1,
                            Category = "Sports",
                            DatePublished = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 63,
                            Title = "Sed ante."
                        },
                        new
                        {
                            Id = new Guid("4470ec76-29f8-4001-acf6-0e04dba01127"),
                            AuthorId = 1,
                            Category = "Entertainment",
                            DatePublished = new DateTime(2021, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Popularity = 58,
                            Title = "Curabitur at ipsum ac tellus semper interdum."
                        });
                });

            modelBuilder.Entity("ArticleDatabaseConnector.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prinz Linacre"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Karol Branford"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Elga Ross"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ericka Fawdery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mahmud Threadgould"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nanete Marwood"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Emmaline Drews"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Susan Downse"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Wilmar Nehl"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jo ann Troubridge"
                        });
                });

            modelBuilder.Entity("ArticleDatabaseConnector.Models.Article", b =>
                {
                    b.HasOne("ArticleDatabaseConnector.Models.Author", null)
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArticleDatabaseConnector.Models.Author", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
